version: '3.7'
services:

  webdriver:
    image: selenoid/chrome:113.0
    ports:
      - '5555:5555'
    networks:
      - tests
    depends_on:
      - selenoid

  selenoid:
    image: aerokube/selenoid:1.10.9
    #network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/root/TESTS/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - tests
  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.9
    #network_mode: bridge
    links:
      - selenoid
    ports:
      - "8001:8001"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - tests


networks:
  tests:
